# testing endpoints
###

POST http://localhost:8080/user/login
content-type: application/json

###

POST http://localhost:8080/user/login
content-type: application/json

{
  "email": "qvasichev3@elegantthemes.com",
  "password": "BWV8qNBX"
}

###
# with invalid token the server should respond with 403 forbidden
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsIm1haWwiOiJxdmFzaWNoZXYzQGVsZWdhbnR0aGVtZXMuY29tIiwiaWF0IjoxNjc1Nzc5NTkzfQ.UQfCCQ96eF_IAqxXFU-r63-Yb4COVBDJG9jGXF4ZlG8

###
GET http://localhost:8080/product

###
# with no token the server should respond with 401 and redirect to login page
GET http://localhost:8080/user

###