GET http://localhost:8080/user

###
POST http://localhost:8080/user/login
content-type: application/json

{
  "email": "qvasichev3@elegantthemes.com",
  "password": "BWV8qNBX"
}

###
GET http://localhost:8080/product

###
POST http://localhost:8080/user