GET http://localhost:8080/product?page=2&limit=9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJxdmFzaWNoZXYzQGVsZWdhbnR0aGVtZXMuY29tIiwicm9sZSI6InVzZXIiLCJzdG9yZUlkIjo5LCJpYXQiOjE2ODA1MzE1MjUsImV4cCI6MTY4MDUzMTgyNX0.izjenjSZ0oZ6OuUabG6oZ5CV48VUNpBvYTW-TKNRvn8

