# testing endpoints
###
GET http://localhost:8080/product

###
# with no token the server should respond with 401 and redirect to login page
GET http://localhost:8080/user

###

POST http://localhost:8080/user/login
content-type: application/json

###

POST http://localhost:8080/user/login
content-type: application/json

{
  "email": "qvasichev3@elegantthemes.com",
  "password": "BWV8qNBX"
}

###
# with invalid token the server should respond with 403 forbidden
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsIm1haWwiOiJxdmFzaWNoZXYzQGVsZWdhbnR0aGVtZXMuY29tIiwiaWF0IjoxNjc1Nzg3MDkyfQ.ijspeVgN5ohJNRvVerNJDR4qBSd1SN-QQspAM499s8A


###

POST http://localhost:8080/user/refreshToken
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJxdmFzaWNoZXYzQGVsZWdhbnR0aGVtZXMuY29tIiwicGFzc3dvcmQiOiJCV1Y4cU5CWCIsInJvbGUiOiJ1c2VyIiwic3RvcmVJZCI6OSwiaWF0IjoxNjc2MDE5MTU5fQ.s7ndn_2D4u-IjXbyf8oyAFsoMw9v7NLUK_fg7_OKZ9g"
}