# testing endpoints
###
GET http://localhost:8080/product

###
# with no token the server should respond with 401 and redirect to login page
GET http://localhost:8080/user

###

POST http://localhost:8080/user/login
content-type: application/json

{
  "email": "sd@sdf.com",
  "password": "BWV8qsdfNBX"
}
###

POST http://localhost:8080/user/login
content-type: application/json

{
  "email": "qvasichev3@elegantthemes.com",
  "password": "BWV8qNBX"
}

###
# with invalid token the server should respond with 403 forbidden
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsIm1haWwiOiJxdmFzaWNoZXYzQGVsZWdhbnR0aGVtZXMuY29tIiwiaWF0IjoxNjc1Nzg3MDkyfQ.ijspeVgN5ohJNRvVerNJDR4qBSd1SN-QQspAM499s8A


###

POST http://localhost:8080/user/refreshToken
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJxdmFzaWNoZXYzQGVsZWdhbnR0aGVtZXMuY29tIiwicm9sZSI6InVzZXIiLCJzdG9yZUlkIjo5LCJpYXQiOjE2ODAxNzI2MDJ9.-X7fZBWqjThRftC9Mn68Pjqr7nhtLovInLq5R3wpRSs"
}