###

POST http://localhost:8080/user/register
content-type: application/json

{
  "email": "magda@salt.se",
  "password": "gargamel",
  "role": "user"
}

###
POST http://localhost:8080/user/register
content-type: application/json

{
  "email": "xchippendale2r@wired.com",
  "password": "QlsbLyx8yBTD",
  "role": "admin"

}

###


POST http://localhost:8080/user/register
content-type: application/json

{
  "email": "andrea@salt.se",
  "password": "italy",
  "role": "admin"
}
